### ISSUE TITLE
Design / Mockup Typewriter

### ISSUE THREAD

**Issue by JasonHoffmann** [common-gold/typewriter#1]
We need an initial typewriter design. This can just be a static image for now, but eventually we may need to slice the image a little to create proper sprites. We can also focus just on the typewriter (and a piece of paper coming out of it) not the container.

**Comment by albertocamacho** [comment]
It would help to know the context - what it's being used for that way the size, color, font etc will be easier to figure out. Doesn't seem that we have a real clear idea of what that may be but I'd recommend figuring it out beforehand.

**Comment by JasonHoffmann** [comment]
I think no matter what it is going to be within a desktop context, either as a chrome extension or some sort of client. But Patrick, Peter, anybody chime in if I'm off bit here. The problem is its kind of chicken and egg, we can't start building until we have images to work off of, but it's hard to design when we don't know what we're building towards. So if we can just start with some basic elements from the typewriter itself that would be more than enough.
