### ISSUE TITLE
Set up basic WebGL / Pixi App

### ISSUE THREAD

**Issue by JasonHoffmann** [common-gold/typewriter#2]
The verdicts still not out on whether or not this should use pixi, but either way we will need an app that just imports the library and sets up a basic app. Will most likely need to set up a basic build process too, but no need to get fancy there.

**Comment by Petroochio** [comment]
I'd like to discuss our general structure too, like what other libraries we need and the whole process. If we use Babel (<3) we will need a different build process. Do we need a framework like React(probs not)? SASS/SCSS/LESS/CSS? How fancy does our webpack config need to be?

Well I guess a lot of this is pending on design. @JasonHoffmann what do you think?

**Comment by JasonHoffmann** [comment]
@Petroochio yea my plan was to use webpack as a real basic ES6 transpiler, really simple JS loaders and run everything with npm scripts. I'd shy away from frameworks since I don't think there will be too many different components and keep the CSS separate (I prefer SASS but open to whatever) so we don't have to set up annoying CSS loaders in webpack. It's like near impossible to keep a webpack config simple, but I'll give it my best shot.

**Comment by Petroochio** [comment]
I have some webpack experience if you need any help there. And I like having a utility library to fall back on, [Ramda](http://ramdajs.com/0.21.0/index.html) is my fav, but I'm pretty open.
