### ISSUE TITLE
Map keyboard to typewriter

### ISSUE THREAD

**Issue by JasonHoffmann** [common-gold/typewriter#4]
This will require a script that maps standard event keycodes on input and maps them to a particular key on the typewriter. Once the basic app is set up and the typewriter rendered in some capacity, it's just a matter of the script logging the proper typewriter key. Not exactly sure how this will work, but I imagine some sort of logic map. For this step, the script just needs to log the proper key, not actually perform any interactions.

**Comment by Petroochio** [comment]
I volunteer as tribute!

**Comment by Petroochio** [comment]
How do we wanna do this?
