### ISSUE TITLE
Make paper move forward on type

### ISSUE THREAD

**Issue by JasonHoffmann** [common-gold/typewriter#6]
The paper needs to slide to the left every time a word is entered. When the end of a line is reached it needs to then slide all the way back and start on the next line.

**Comment by patleeman** [comment]
I'll try taking a stab at this.

**Comment by patleeman** [comment]
I merged into master what I have so far.  

I was able to get the paper to follow the cursor both when typing and backspacing.  There is a bug when backspacing where the cursor position hangs.  You can see it here:

![output](https://cloud.githubusercontent.com/assets/11035426/17309116/48a98506-580b-11e6-8201-751e6cc0b6ef.gif)

Not sure whats causing that.
